import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Busi & Josh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hand-in-hand.png" />
      </Head>
      <Nav>
        
      </Nav>
      <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
      
    </>
  )
}
